### PR TITLE
Fix #1 NRE and missing bool type

### LINKED ISSUE #1: NullReferenceException in CppParser.ParseFile
I am trying to parse this file: https://github.com/lemire/simdjson/blob/master/singleheader/simdjson.h (simdjson single header).  using the following code:
```csharp
var cpo = new CppParserOptions();
cpo.ConfigureForWindowsMsvc(CppTargetCpu.X86_64); 
//btw, I'd made ConfigureForWindowsMsvc static + fluent interface :-) 
cpo.AdditionalArguments.Add("-std=c++17");
var compilation = CppParser.ParseFile(@"C:\prj\simdjson.h", cpo);
```
but getting an NRE.
The lib looks great! CppSharp is not that easy to use

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes #1. Not sure about that `return null` but it works.

### CODE REVIEW

**Comment by EgorBo** [comment]
Ah, I see 🙂

**Comment by xoofx** [comment]
but I would not mind having the CppPrimitive.Bool fix? 😅

**Comment by xoofx** [comment]
Nevermind gonna push it

**Comment by EgorBo** [comment]
@xoofx thanks! Tried 0.1.1 - it works but at some points throws InvalidOE because of that bool 🙂

**Comment by xoofx** [comment]
yeah sorry for this bug, it's fixed by `0.1.3` ;)

**Pull request closed without merging**
